#!/usr/bin/env node
// build-public.js — same reasoning as build-template.js: a Worker has no
// filesystem, so the wizard's HTML/CSS/JS (public/*) get embedded as
// plain string constants at build time instead of being read off disk
// at request time. Re-run after editing anything under public/.
//   node scripts/build-public.js
// (wrapped by `npm run build:public`)

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PUBLIC_DIR = path.join(__dirname, "..", "public");
const OUT_FILE = path.join(__dirname, "..", "src", "lib", "public-embed.generated.js");

const files = {
  WIZARD_HTML: fs.readFileSync(path.join(PUBLIC_DIR, "index.html"), "utf8"),
  WIZARD_JS: fs.readFileSync(path.join(PUBLIC_DIR, "wizard.js"), "utf8"),
  WIZARD_CSS: fs.readFileSync(path.join(PUBLIC_DIR, "wizard.css"), "utf8"),
};

const body =
  "// AUTO-GENERATED by scripts/build-public.js — do not hand-edit.\n" +
  "// Re-run that script after changing anything under public/.\n\n" +
  Object.entries(files)
    .map(([name, content]) => `const ${name} = ${JSON.stringify(content)};`)
    .join("\n\n") +
  "\n\nexport { " + Object.keys(files).join(", ") + " };\n";

fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
fs.writeFileSync(OUT_FILE, body);
console.log(`Wrote ${OUT_FILE} (${Buffer.byteLength(body)} bytes)`);
